#!/bin/bash -e

PKG=/tmp/minesweeper-$(date +%F_%T).zip

zip -r $PKG ./dist

SIZE=$( echo $(du --bytes $PKG) | cut -d' ' -f1 )
MAX=$(( 1024 * 13 ))

echo "$SIZE = $(echo "scale=2; ($SIZE*100)/$MAX" | bc -l )%"
